spring:
  application:
    name: front

  mvc:
    static-path-pattern: /static/**

server:
  port: 8080

eureka-server:
  host: localhost
  port: 8761
  postfix: default

eureka:
  user:
    name: admin
    password: 1234

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}:${eureka-server.port}/eureka

    registry-fetch-interval-seconds: 30

    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
    enabled: false

---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live
55g:
  log:
    path: /logs/live/front

logging:
  file:
    name: ${55g.log.path}/front-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/front-live-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: info
    shop.S5G.shop: info

eureka:
  client:
    enabled: true
---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8580

55g:
  log:
    path: /logs/dev/front

logging:
  file:
    name: ${55g.log.path}/front-dev.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/front-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    shop.S5G.shop: trace

eureka:
  client:
    enabled: true
---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka