spring:
  profiles:
    active: default

  application:
    name: front

  mvc:
    static-path-pattern: /static/**

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

gateway:
  url: http://localhost:8000

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050