spring:
  profiles:
    active: default

  application:
    name: front

  mvc:
    static-path-pattern: /static/**

  config:
    import: configserver:http://admin:55g.com7@localhost:9000

  cloud:
    config:
      label: main