spring:
  application:
    name: front

  mvc:
    static-path-pattern: /static/**

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  rabbitmq:
    host: host
    port: 0
    username: username
    password: password

image:
  appkey: appkey
  secretKey: secretKey

gateway:
  url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh

rabbit:
  exchange:
    orders: 55g.orders.exchange
    coupon: 55g.coupon.exchange
    category: 55g.category.coupon.exchange
  route:
    orders:
      payment:
        toss: 55g.orders.payment.toss
    coupon:
      create: 55g.coupon.create
    category:
      coupon: 55g.category.coupon.create

redis:
  host: localhost
  port: 6379
  password: ''

oauth:
  payco:
    auth-url: https://id.payco.com/oauth2.0/authorize
    client-id: 3RDZzEkOENyj7mThJCsfZ1i
    login-redirect-url: https://www.55g.shop/payco/callback
    link-redirect-url: https://www.55g.shop/payco/link
---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050

---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker
---
spring:
  config:
    activate:
      on-profile: local

rabbit:
  route:
    orders:
      payment:
        toss: 55g.dev.orders.payment.toss
---
spring:
  config:
    activate:
      on-profile: test

  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full

rabbit:
  route:
    orders:
      payment:
        toss: 55g.dev.f3fort.orders.payment.toss
---
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
