spring:
  application:
    name: 55g.com-front

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: "classpath:/resources/static, /static"

55g:
  log:
    path: .
logging:
  file:
    name: ${55g.log.path}/front.log
---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live

logging:
  file:
    name: ${55g.log.path}/front-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/front-live-%d{yyyy-MM-dd_HH:mm}.%i.log
      max-file-size: 100KB
  level:
    root: info
    shop.S5G.shop: info
55g:
  log:
    path: /logs/live/front
---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev
logging:
  file:
    name: ${55g.log.path}/front-dev.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/front-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    shop.S5G.shop: trace

55g:
  log:
    path: /logs/dev/front
---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker
